name = "CcallableRecorder"
uuid = "c4ea9ff0-0b32-41e1-90aa-c02ffe0a7e2d"
authors = ["Kristoffer <kcarlsson89@gmail.com>"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"

[compat]
ExprTools = "0.1.8"
